const headlineTemplates = [
  "Why {name} is {location}'s Sweetest Spot in 2025",
  "Discover Why {name} Rules {location}'s Dessert Scene",
  "{location} Locals Can’t Stop Talking About {name}",
  "{name}: Baking Up Buzz in the City of Dreams",
  "Where Every Bite is Bliss – {name}, {location}",
  "{name} Brings Homemade Happiness to {location}",
  "How {name} Became {location}'s Favorite Treat Stop",
  "{name}: A Must-Visit Destination in {location}",
  "The Secret Behind {name}'s Success in {location}",
  "From Local Favorite to Legend – {name}, {location}",
  "How {name} is Changing the Way ${location} Eats",
  "{name} Is Taking {location}'s Food Scene by Storm",
  "Top 5 Reasons {name} is Loved by {location} Locals",
  "{location} Just Got Sweeter Thanks to {name}",
  "What Makes {name} Stand Out in {location}",
  "The Buzz Around {name} in {location} is Real",
  "{name}: The Local Brand Everyone in {location} Talks About",
  "Craving Happiness? Try {name} in {location}",
  "Here’s Why Everyone’s Visiting {name} in {location}",
  "{location}'s Hidden Gem: Welcome to {name}",
  "A Delicious Revolution: {name} in {location}",
  "Why {location} Can't Get Enough of {name}",
  "What Locals Are Saying About {name} in {location}",
  "{name} – Redefining Local Taste in {location}",
  "{name} is More Than a Shop – It's a {location} Experience",
  "Delighting {location}, One Bite at a Time: {name}",
  "Sweet Surprises Await at {name}, {location}",
  "Locals Swear by {name}'s Quality in {location}",
  "{name} Sets the Bar for Bakeries in {location}",
  "Experience Freshness Like Never Before at {name}, {location}",
  "Why {name} is on Every {location} Foodie's List"
];

module.exports = headlineTemplates;
