const headlineTemplates = [
  "Why {name} is {location}'s Favorite Spot in 2025",
  "Discover Why {name} Leads {location}'s Business Scene",
  "{location} Locals Can’t Stop Talking About {name}",
  "{name}: Making Waves in the City of Dreams",
  "Where Quality Meets Service – {name}, {location}",
  "{name} Brings Exceptional Service to {location}",
  "How {name} Became a Local Icon in {location}",
  "{name}: A Must-Visit in {location}",
  "The Secret Behind {name}'s Local Success",
  "From Hidden Gem to Household Name – {name}, {location}",
  "How {name} is Changing the Way {location} Shops",
  "{name} Is Transforming {location}'s Local Market",
  "Top 5 Reasons Locals Love {name} in {location}",
  "{location} Just Got Better Thanks to {name}",
  "What Makes {name} a Standout in {location}",
  "The Buzz Around {name} in {location} is Growing",
  "{name}: The Local Business Everyone in {location} Knows",
  "Need Quality? Visit {name} in {location}",
  "Here’s Why Everyone’s Choosing {name} in {location}",
  "{location}'s Trusted Name: {name}",
  "A Local Favorite: {name} in {location}",
  "Why {location} Can’t Stop Raving About {name}",
  "What {location} Locals Say About {name}",
  "{name}: Redefining Local Excellence in {location}",
  "{name} is More Than a Brand – It's a {location} Experience",
  "Serving {location} with Pride: {name}",
  "Great Service, Great Reviews – That’s {name}, {location}",
  "Locals Count on {name}'s Excellence in {location}",
  "{name} Sets the Standard for Local Service in {location}",
  "Experience Service Like Never Before at {name}, {location}",
  "Why {name} is on Every {location} Local’s List"
];


module.exports = headlineTemplates;
